import type { CSSProperties } from "react";
import type { ThemeConfig } from "antd";

export const designTokens = {
  colors: {
    primary: "#414099",
    secondary: "#0cc496",
    danger: "#ff2032",
    warning: "#f0b100",
    background: "#ffffff",
    backgroundLayout: "#f6f5fb",
    backgroundSubtle: "#f3f5f8",
    backgroundElevated: "#ffffff",
    text: "#171717",
    textDarkMode: "#ededed",
    textNeutral: "#35363a",
    textHeading: "#1d1b4a",
    textSecondary: "#6b6a8f",
    border: "#d1d6de",
    borderSecondary: "#ebe9f7",
    scrollbarTrack: "#ebe9e9",
    scrollbarThumb: "#8b5cf6",
    scrollbarThumbHover: "#7c3aed",
  },
  typography: {
    fontFamily: "var(--font-work-sans), Arial, sans-serif",
    fontFamilyCode: "var(--font-work-sans), Arial, sans-serif",
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontWeightSemibold: 600,
    caption: { fontSize: 12, lineHeight: 1.5 },
    body: { fontSize: 14, lineHeight: 1.5 },
    subtitle: { fontSize: 16, lineHeight: 1.5 },
    title: { fontSize: 32, lineHeight: 1.25 },
    heading2: { fontSize: 24, lineHeight: 1.3 },
    heading3: { fontSize: 20, lineHeight: 1.35 },
  },
  border: {
    width: 1,
    widthStrong: 2,
    radiusSmall: 8,
    radius: 10,
    radiusLarge: 14,
    radiusXLarge: 18,
    radiusPill: 999,
  },
  spacing: {
    xxs: 4,
    xs: 8,
    small: 12,
    base: 16,
    medium: 20,
    large: 24,
    xlarge: 32,
  },
  shadows: {
    subtle: "0 8px 28px rgba(65, 64, 153, 0.06)",
    card: "0 16px 40px rgba(65, 64, 153, 0.1)",
    elevated: "0 20px 60px rgba(65, 64, 153, 0.08)",
    overlay: "0 30px 80px rgba(16, 18, 56, 0.18)",
    button: "0 10px 22px rgba(65, 64, 153, 0.14)",
    buttonFocus: "rgba(65, 64, 153, 0.22)",
  },
  controls: {
    buttonMinWidth: 112,
    buttonHeight: 44,
  },
} as const;

export const appTheme: ThemeConfig = {
  cssVar: {
    prefix: "app",
    key: "ui-components",
  },
  token: {
    colorPrimary: designTokens.colors.primary,
    colorSuccess: designTokens.colors.secondary,
    colorError: designTokens.colors.danger,
    colorWarning: designTokens.colors.warning,
    colorInfo: designTokens.colors.primary,
    colorBgBase: designTokens.colors.background,
    colorBgLayout: designTokens.colors.backgroundLayout,
    colorBgContainer: designTokens.colors.background,
    colorBgElevated: designTokens.colors.backgroundElevated,
    colorFillAlter: designTokens.colors.backgroundSubtle,
    colorText: designTokens.colors.textNeutral,
    colorTextHeading: designTokens.colors.textHeading,
    colorTextSecondary: designTokens.colors.textSecondary,
    colorTextDescription: designTokens.colors.textSecondary,
    colorBorder: designTokens.colors.border,
    colorBorderSecondary: designTokens.colors.borderSecondary,
    colorSplit: designTokens.colors.borderSecondary,
    fontFamily: designTokens.typography.fontFamily,
    fontFamilyCode: designTokens.typography.fontFamilyCode,
    fontSize: designTokens.typography.body.fontSize,
    fontSizeSM: designTokens.typography.caption.fontSize,
    fontSizeLG: designTokens.typography.subtitle.fontSize,
    fontSizeHeading1: designTokens.typography.title.fontSize,
    fontSizeHeading2: designTokens.typography.heading2.fontSize,
    fontSizeHeading3: designTokens.typography.heading3.fontSize,
    fontSizeHeading4: designTokens.typography.subtitle.fontSize,
    fontSizeHeading5: designTokens.typography.body.fontSize,
    lineHeight: designTokens.typography.body.lineHeight,
    lineHeightSM: designTokens.typography.caption.lineHeight,
    lineHeightLG: designTokens.typography.subtitle.lineHeight,
    lineHeightHeading1: designTokens.typography.title.lineHeight,
    lineHeightHeading2: designTokens.typography.heading2.lineHeight,
    lineHeightHeading3: designTokens.typography.heading3.lineHeight,
    fontWeightStrong: designTokens.typography.fontWeightSemibold,
    lineWidth: designTokens.border.width,
    borderRadius: designTokens.border.radius,
    borderRadiusSM: designTokens.border.radiusSmall,
    borderRadiusLG: designTokens.border.radiusLarge,
    boxShadow: designTokens.shadows.overlay,
    boxShadowSecondary: designTokens.shadows.card,
    boxShadowTertiary: designTokens.shadows.subtle,
    controlHeight: 40,
    controlHeightLG: 44,
    controlHeightSM: 32,
    paddingXXS: designTokens.spacing.xxs,
    paddingXS: designTokens.spacing.xs,
    paddingSM: designTokens.spacing.small,
    padding: designTokens.spacing.base,
    paddingMD: designTokens.spacing.medium,
    paddingLG: designTokens.spacing.large,
  },
  components: {
    Typography: {
      titleMarginTop: 0,
      titleMarginBottom: designTokens.spacing.small,
    },
    Button: {
      controlHeight: 42,
      borderRadius: designTokens.border.radius,
      fontSize: designTokens.typography.subtitle.fontSize,
      fontWeight: designTokens.typography.fontWeightSemibold,
      contentLineHeight: 1.2,
      paddingInline: designTokens.spacing.xs,
      primaryShadow: designTokens.shadows.button,
    },
    Card: {
      bodyPadding: designTokens.spacing.large,
      headerFontSize: designTokens.typography.subtitle.fontSize,
    },
    Modal: {
      borderRadiusLG: designTokens.border.radiusXLarge,
      boxShadow: designTokens.shadows.overlay,
    },
  },
};

export const themeCssVariables: CSSProperties & Record<`--${string}`, string | number> = {
  "--app-color-bg-layout": designTokens.colors.backgroundLayout,
  "--app-color-text": designTokens.colors.text,
  "--app-color-text-dark-mode": designTokens.colors.textDarkMode,
  "--app-color-primary": designTokens.colors.primary,
  "--app-color-secondary": designTokens.colors.secondary,
  "--app-color-danger": designTokens.colors.danger,
  "--app-color-neutral-border": designTokens.colors.border,
  "--app-color-neutral-text": designTokens.colors.textNeutral,
  "--app-color-neutral-surface": designTokens.colors.backgroundSubtle,
  "--app-color-scrollbar-track": designTokens.colors.scrollbarTrack,
  "--app-color-scrollbar-thumb": designTokens.colors.scrollbarThumb,
  "--app-color-scrollbar-thumb-hover": designTokens.colors.scrollbarThumbHover,
  "--app-font-family": designTokens.typography.fontFamily,
  "--app-font-family-code": designTokens.typography.fontFamilyCode,
  "--app-font-size-body": `${designTokens.typography.body.fontSize}px`,
  "--app-line-height-body": designTokens.typography.body.lineHeight,
  "--app-border-width": `${designTokens.border.width}px`,
  "--app-border-radius": `${designTokens.border.radius}px`,
  "--app-box-shadow": designTokens.shadows.card,
  "--product-button-min-width": `${designTokens.controls.buttonMinWidth}px`,
  "--product-button-min-height": `${designTokens.controls.buttonHeight}px`,
  "--product-button-letter-spacing": "0.01em",
  "--product-button-shadow": designTokens.shadows.button,
  "--product-button-focus-outline": designTokens.shadows.buttonFocus,
};
