import type { CSSProperties } from "react";
import type { ThemeConfig } from "antd";

export const designTokens = {
  colors: {
    primary: "#414099",
    secondary: "#0cc496",
    danger: "#ff2032",
    warning: "#f0b100",
    background: "#ffffff",
    backgroundLayout: "#f6f5fb",
    backgroundSubtle: "#f3f5f8",
    backgroundElevated: "#ffffff",
    text: "#171717",
    textDarkMode: "#ededed",
    textNeutral: "#35363a",
    textHeading: "#1d1b4a",
    textSecondary: "#6b6a8f",
    border: "#d1d6de",
    borderSecondary: "#ebe9f7",
    scrollbarTrack: "#ebe9e9",
    scrollbarThumb: "#8b5cf6",
    scrollbarThumbHover: "#7c3aed",
  },
  productColors: {
    heading: "#332556",
    headingMuted: "rgba(51, 37, 86, 0.6)",
    headingFaded: "rgba(51, 37, 86, 0.45)",
    headingDisabled: "#332556b2",
    titleDark: "#2c275f",
    muted: "#8d8cab",
    primaryAccent: "#4b49b6",
    primaryAccentStrong: "#4b49c6",
    primaryIcon: "#3d3ccc",
    dangerAccent: "#ed1b2f",
    positiveAccent: "#1cb791",
    warningAccent: "#a65f00",
    negativeAccent: "#db3529",
    progressDanger: "#ef4339",
    progressSuccess: "#12b347",
    progressWarning: "#f0b126",
    successStrong: "#008236",
    dangerStrong: "#c10007",
    surfaceTint: "#f8f8ff",
    surfaceSoft: "#f3f2fb",
    surfaceHighlight: "#f0f0ff",
    controlBorder: "#d9d9d9",
    separator: "#ece8fb",
    separatorAlt: "#e7e4f6",
    mutedAlt: "#8d88a8",
    alert: "#ff2432",
    disabledText: "#b8b5c8",
    disabledTextSoft: "#d1cfd9",
    statSurfaceActive: "#deddff",
    statBorderActive: "#d2d0fb",
    successSurface: "#dcfce7",
    warningSurface: "#fef9c2",
    dangerSurface: "#ffe2e2",
    successTintSoft: "rgba(12, 196, 150, 0.1)",
    dangerTintSoft: "rgba(237, 27, 47, 0.1)",
    warningTintSoft: "rgba(240, 177, 0, 0.1)",
    successTint: "rgba(12, 196, 150, 0.12)",
    successTintAlt: "rgba(43, 204, 164, 0.20)",
    dangerTint: "rgba(237, 27, 47, 0.12)",
    contrastBorder: "rgba(255, 255, 255, 0.2)",
    primaryBorderSubtle: "#4140991a",
    primaryAlpha05: "rgba(65, 64, 153, 0.05)",
    primaryAlpha08: "rgba(65, 64, 153, 0.08)",
    primaryAlpha10: "rgba(65, 64, 153, 0.1)",
    primaryAlpha12: "rgba(65, 64, 153, 0.12)",
    primaryAlpha15: "rgba(65, 64, 153, 0.15)",
    primaryAlpha20: "rgba(65, 64, 153, 0.2)",
    primaryAlpha35: "rgba(65, 64, 153, 0.35)",
  },
  typography: {
    fontFamily: "var(--font-work-sans), Arial, sans-serif",
    fontFamilyCode: "var(--font-work-sans), Arial, sans-serif",
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontWeightSemibold: 600,
    fontWeightBold: 700,
    micro: { fontSize: 11, lineHeight: 1.4 },
    caption: { fontSize: 12, lineHeight: 1.5 },
    bodySmall: { fontSize: 13, lineHeight: 1.5 },
    body: { fontSize: 14, lineHeight: 1.5 },
    bodyLarge: { fontSize: 15, lineHeight: 1.5 },
    subtitle: { fontSize: 16, lineHeight: 1.5 },
    heading4: { fontSize: 18, lineHeight: 1.35 },
    title: { fontSize: 32, lineHeight: 1.25 },
    heading2: { fontSize: 24, lineHeight: 1.3 },
    heading3: { fontSize: 20, lineHeight: 1.35 },
  },
  border: {
    width: 1,
    widthStrong: 2,
    radiusSmall: 8,
    radius: 10,
    radiusLarge: 14,
    radiusXLarge: 18,
    radiusPill: 999,
  },
  spacing: {
    xxs: 4,
    xs: 8,
    small: 12,
    base: 16,
    medium: 20,
    large: 24,
    xlarge: 32,
  },
  shadows: {
    subtle: "0 8px 28px rgba(65, 64, 153, 0.06)",
    card: "0 16px 40px rgba(65, 64, 153, 0.1)",
    elevated: "0 20px 60px rgba(65, 64, 153, 0.08)",
    overlay: "0 30px 80px rgba(16, 18, 56, 0.18)",
    button: "0 10px 22px rgba(65, 64, 153, 0.14)",
    buttonFocus: "rgba(65, 64, 153, 0.22)",
    sidebarActive: "0 10px 7.5px rgba(0, 0, 0, 0.1), 0 4px 3px rgba(0, 0, 0, 0.1)",
    tag: "0 1px 3px 0 rgba(0, 0, 0, 0.10), 0 1px 2px -1px rgba(0, 0, 0, 0.10)",
    notificationRing: "0 0 0 2px #ffffff",
  },
  controls: {
    buttonMinWidth: 112,
    buttonHeight: 44,
    buttonGroupItemMinWidth: 140,
  },
} as const;

export const appTheme: ThemeConfig = {
  cssVar: {
    prefix: "app",
    key: "ui-components",
  },
  token: {
    colorPrimary: designTokens.colors.primary,
    colorSuccess: designTokens.colors.secondary,
    colorError: designTokens.colors.danger,
    colorWarning: designTokens.colors.warning,
    colorInfo: designTokens.colors.primary,
    colorBgBase: designTokens.colors.background,
    colorBgLayout: designTokens.colors.backgroundLayout,
    colorBgContainer: designTokens.colors.background,
    colorBgElevated: designTokens.colors.backgroundElevated,
    colorFillAlter: designTokens.colors.backgroundSubtle,
    colorText: designTokens.colors.textNeutral,
    colorTextHeading: designTokens.colors.textHeading,
    colorTextSecondary: designTokens.colors.textSecondary,
    colorTextDescription: designTokens.colors.textSecondary,
    colorBorder: designTokens.colors.border,
    colorBorderSecondary: designTokens.colors.borderSecondary,
    colorSplit: designTokens.colors.borderSecondary,
    fontFamily: designTokens.typography.fontFamily,
    fontFamilyCode: designTokens.typography.fontFamilyCode,
    fontSize: designTokens.typography.body.fontSize,
    fontSizeSM: designTokens.typography.caption.fontSize,
    fontSizeLG: designTokens.typography.subtitle.fontSize,
    fontSizeHeading1: designTokens.typography.title.fontSize,
    fontSizeHeading2: designTokens.typography.heading2.fontSize,
    fontSizeHeading3: designTokens.typography.heading3.fontSize,
    fontSizeHeading4: designTokens.typography.subtitle.fontSize,
    fontSizeHeading5: designTokens.typography.body.fontSize,
    lineHeight: designTokens.typography.body.lineHeight,
    lineHeightSM: designTokens.typography.caption.lineHeight,
    lineHeightLG: designTokens.typography.subtitle.lineHeight,
    lineHeightHeading1: designTokens.typography.title.lineHeight,
    lineHeightHeading2: designTokens.typography.heading2.lineHeight,
    lineHeightHeading3: designTokens.typography.heading3.lineHeight,
    fontWeightStrong: designTokens.typography.fontWeightSemibold,
    lineWidth: designTokens.border.width,
    borderRadius: designTokens.border.radius,
    borderRadiusSM: designTokens.border.radiusSmall,
    borderRadiusLG: designTokens.border.radiusLarge,
    boxShadow: designTokens.shadows.overlay,
    boxShadowSecondary: designTokens.shadows.card,
    boxShadowTertiary: designTokens.shadows.subtle,
    controlHeight: 40,
    controlHeightLG: 44,
    controlHeightSM: 32,
    paddingXXS: designTokens.spacing.xxs,
    paddingXS: designTokens.spacing.xs,
    paddingSM: designTokens.spacing.small,
    padding: designTokens.spacing.base,
    paddingMD: designTokens.spacing.medium,
    paddingLG: designTokens.spacing.large,
  },
  components: {
    Typography: {
      titleMarginTop: 0,
      titleMarginBottom: designTokens.spacing.small,
    },
    Button: {
      controlHeight: 42,
      borderRadius: designTokens.border.radius,
      fontSize: designTokens.typography.subtitle.fontSize,
      fontWeight: designTokens.typography.fontWeightSemibold,
      contentLineHeight: 1.2,
      paddingInline: designTokens.spacing.xs,
      primaryShadow: designTokens.shadows.button,
    },
    Card: {
      bodyPadding: designTokens.spacing.large,
      headerFontSize: designTokens.typography.subtitle.fontSize,
    },
    Modal: {
      borderRadiusLG: designTokens.border.radiusXLarge,
      boxShadow: designTokens.shadows.overlay,
    },
  },
};

export const themeCssVariables: CSSProperties & Record<`--${string}`, string | number> = {
  "--app-color-bg-layout": designTokens.colors.backgroundLayout,
  "--app-color-bg-container": designTokens.colors.background,
  "--app-color-text": designTokens.colors.text,
  "--app-color-text-dark-mode": designTokens.colors.textDarkMode,
  "--app-color-text-secondary": designTokens.colors.textSecondary,
  "--app-color-text-light-solid": designTokens.colors.background,
  "--app-color-primary": designTokens.colors.primary,
  "--app-color-secondary": designTokens.colors.secondary,
  "--app-color-danger": designTokens.colors.danger,
  "--app-color-success": designTokens.colors.secondary,
  "--app-color-error": designTokens.colors.danger,
  "--app-color-warning": designTokens.colors.warning,
  "--app-color-neutral-border": designTokens.colors.border,
  "--app-color-neutral-text": designTokens.colors.textNeutral,
  "--app-color-neutral-surface": designTokens.colors.backgroundSubtle,
  "--app-color-border-secondary": designTokens.colors.borderSecondary,
  "--app-color-scrollbar-track": designTokens.colors.scrollbarTrack,
  "--app-color-scrollbar-thumb": designTokens.colors.scrollbarThumb,
  "--app-color-scrollbar-thumb-hover": designTokens.colors.scrollbarThumbHover,
  "--app-font-family": designTokens.typography.fontFamily,
  "--app-font-family-code": designTokens.typography.fontFamilyCode,
  "--app-font-size-micro": `${designTokens.typography.micro.fontSize}px`,
  "--app-font-size-caption": `${designTokens.typography.caption.fontSize}px`,
  "--app-font-size-body-small": `${designTokens.typography.bodySmall.fontSize}px`,
  "--app-font-size-body": `${designTokens.typography.body.fontSize}px`,
  "--app-font-size-body-large": `${designTokens.typography.bodyLarge.fontSize}px`,
  "--app-font-size-subtitle": `${designTokens.typography.subtitle.fontSize}px`,
  "--app-font-size-heading-4": `${designTokens.typography.heading4.fontSize}px`,
  "--app-font-size-heading-3": `${designTokens.typography.heading3.fontSize}px`,
  "--app-font-size-heading-2": `${designTokens.typography.heading2.fontSize}px`,
  "--app-font-size-title": `${designTokens.typography.title.fontSize}px`,
  "--app-font-weight-regular": designTokens.typography.fontWeightRegular,
  "--app-font-weight-medium": designTokens.typography.fontWeightMedium,
  "--app-font-weight-semibold": designTokens.typography.fontWeightSemibold,
  "--app-font-weight-bold": designTokens.typography.fontWeightBold,
  "--app-line-height-body": designTokens.typography.body.lineHeight,
  "--app-border-width": `${designTokens.border.width}px`,
  "--app-border-radius-sm": `${designTokens.border.radiusSmall}px`,
  "--app-border-radius": `${designTokens.border.radius}px`,
  "--app-border-radius-lg": `${designTokens.border.radiusLarge}px`,
  "--app-border-radius-pill": `${designTokens.border.radiusPill}px`,
  "--app-box-shadow": designTokens.shadows.card,
  "--app-box-shadow-tertiary": designTokens.shadows.subtle,
  "--app-box-shadow-overlay": designTokens.shadows.overlay,
  "--ui-color-heading": designTokens.productColors.heading,
  "--ui-color-heading-muted": designTokens.productColors.headingMuted,
  "--ui-color-heading-faded": designTokens.productColors.headingFaded,
  "--ui-color-heading-disabled": designTokens.productColors.headingDisabled,
  "--ui-color-title-dark": designTokens.productColors.titleDark,
  "--ui-color-muted": designTokens.productColors.muted,
  "--ui-color-primary-accent": designTokens.productColors.primaryAccent,
  "--ui-color-primary-accent-strong": designTokens.productColors.primaryAccentStrong,
  "--ui-color-primary-icon": designTokens.productColors.primaryIcon,
  "--ui-color-danger-accent": designTokens.productColors.dangerAccent,
  "--ui-color-positive-accent": designTokens.productColors.positiveAccent,
  "--ui-color-warning-accent": designTokens.productColors.warningAccent,
  "--ui-color-negative-accent": designTokens.productColors.negativeAccent,
  "--ui-color-progress-danger": designTokens.productColors.progressDanger,
  "--ui-color-progress-success": designTokens.productColors.progressSuccess,
  "--ui-color-progress-warning": designTokens.productColors.progressWarning,
  "--ui-color-success-strong": designTokens.productColors.successStrong,
  "--ui-color-danger-strong": designTokens.productColors.dangerStrong,
  "--ui-color-surface-tint": designTokens.productColors.surfaceTint,
  "--ui-color-surface-soft": designTokens.productColors.surfaceSoft,
  "--ui-color-surface-highlight": designTokens.productColors.surfaceHighlight,
  "--ui-color-control-border": designTokens.productColors.controlBorder,
  "--ui-color-separator": designTokens.productColors.separator,
  "--ui-color-separator-alt": designTokens.productColors.separatorAlt,
  "--ui-color-muted-alt": designTokens.productColors.mutedAlt,
  "--ui-color-alert": designTokens.productColors.alert,
  "--ui-color-disabled-text": designTokens.productColors.disabledText,
  "--ui-color-disabled-text-soft": designTokens.productColors.disabledTextSoft,
  "--ui-color-stat-surface-active": designTokens.productColors.statSurfaceActive,
  "--ui-color-stat-border-active": designTokens.productColors.statBorderActive,
  "--ui-color-success-surface": designTokens.productColors.successSurface,
  "--ui-color-warning-surface": designTokens.productColors.warningSurface,
  "--ui-color-danger-surface": designTokens.productColors.dangerSurface,
  "--ui-color-success-tint-soft": designTokens.productColors.successTintSoft,
  "--ui-color-danger-tint-soft": designTokens.productColors.dangerTintSoft,
  "--ui-color-warning-tint-soft": designTokens.productColors.warningTintSoft,
  "--ui-color-success-tint": designTokens.productColors.successTint,
  "--ui-color-success-tint-alt": designTokens.productColors.successTintAlt,
  "--ui-color-danger-tint": designTokens.productColors.dangerTint,
  "--ui-color-contrast-border": designTokens.productColors.contrastBorder,
  "--ui-color-primary-border-subtle": designTokens.productColors.primaryBorderSubtle,
  "--ui-color-primary-alpha-05": designTokens.productColors.primaryAlpha05,
  "--ui-color-primary-alpha-08": designTokens.productColors.primaryAlpha08,
  "--ui-color-primary-alpha-10": designTokens.productColors.primaryAlpha10,
  "--ui-color-primary-alpha-12": designTokens.productColors.primaryAlpha12,
  "--ui-color-primary-alpha-15": designTokens.productColors.primaryAlpha15,
  "--ui-color-primary-alpha-20": designTokens.productColors.primaryAlpha20,
  "--ui-color-primary-alpha-35": designTokens.productColors.primaryAlpha35,
  "--ui-button-min-width": `${designTokens.controls.buttonMinWidth}px`,
  "--ui-button-min-height": `${designTokens.controls.buttonHeight}px`,
  "--ui-button-letter-spacing": "0.01em",
  "--ui-button-shadow": designTokens.shadows.button,
  "--ui-button-focus-outline": designTokens.shadows.buttonFocus,
  "--ui-sidebar-active-shadow": designTokens.shadows.sidebarActive,
  "--ui-tag-shadow": designTokens.shadows.tag,
  "--ui-notification-ring": designTokens.shadows.notificationRing,
  "--ui-button-group-item-min-width": `${designTokens.controls.buttonGroupItemMinWidth}px`,
};
